[package]
name = "must_destroy"
description = "simple forced explcit destructors"
license = "MIT"
version = "0.1.0"
authors = ["Sekhat Temporus <sekhat@temporus.me>"]
edition = "2018"
repository = "https://github.com/sekhat/must_destroy"

[dependencies]
